name: Frontend Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-robot-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdrivermanager

      - name: Run Robot Framework Tests
        run: |
          robot -d logs tests/
        working-directory: ${{ github.workspace }}

      - name: Upload Robot Framework Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: logs